service: sls-layers-microservice

frameworkVersion: "2"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  region: ap-south-1

layers:
  logging:
    path: logging
    description: Logging Layer
    retain: true # optional, false by default. If true, layer versions are not deleted as new ones are created
  core:
    path: core
    description: Core Layer - AWS Utils
    retain: true # optional, false by default. If true, layer versions are not deleted as new ones are created
